server:
  port: 8503

spring:
  application:
    name: notification-service
  rabbitmq:
    username: imenez
    password: imenez
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
