server:
  port: 8502

spring:
  application:
    name: ticket-server
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    username: imenez
    password: imenez
    cloud:
      stream:
        bindings:
          output:
            destination: msqueue
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/